### ISSUE TITLE
JOSS Review: package version

### ISSUE THREAD

**Issue by draabe** [pfeinsper/drone-swarm-search#259]
Hi,

just a quick question: the package version stated for the JOSS review (https://github.com/openjournals/joss-reviews/issues/6746) is 1.1.7, which is quite off from the last version release (0.2.2).

Am I missing something here?

Thanks!

**Comment by RicardoRibeiroRodrigues** [comment]
Hi,
the 1.1.7 version on pypi was the latest version at the time we were submitting the paper, but now we are at 1.1.9 (just some bug fixes em documentation updates). About the releases, we end up forgetting to update the github releases, only made the tags. I just made the github 1.1.9 release, so feel free to use it for review purposes.
Thanks for the feedback.

**Comment by draabe** [comment]
Thanks for resolving!
