### ISSUE TITLE
JOSS: running tests

### ISSUE THREAD

**Issue by wob86** [pfeinsper/drone-swarm-search#266]
Good to see that within DSSE folder there is a set of tests, but there is no documentation that I found that describes how to run them and in what order (Im assuming its a suite of tests?).  Would be useful way to test code once installed and if anyone in the future makes changes

**Comment by renatex333** [comment]
Hi @wob86,

Thank you for pointing! Indeed, we missed including directions regarding how to run the tests in the DSSE folder. I've now added a brief explanation in the README file on how to run them. Could you please take a look and let me know if you think it's sufficient? It's in PR #267 

Thank you for your feedback!

**Comment by wob86** [comment]
Yes thats great, nice discription of the tests and how to run them.  Thanks
